### ISSUE TITLE
Neallokovat dynamicky, když není potřeba

### ISSUE THREAD

**Issue by fan1x** [Listonoh/antColonyCpp#11]
např: https://github.com/Listonoh/antColonyCpp/blob/b2940eacb198bf486ac3827900bda433b569fce9/ant2/ant2.cpp#L46

https://github.com/Listonoh/antColonyCpp/blob/b2940eacb198bf486ac3827900bda433b569fce9/ant2/ant2.cpp#L155

...

**Comment by Listonoh** [comment]
https://github.com/Listonoh/antColonyCpp/blob/2244d93d60e6623f5a1cfc1f1bd445d4c5a4a105/ant2/ant2.cpp#L42

https://github.com/Listonoh/antColonyCpp/blob/2244d93d60e6623f5a1cfc1f1bd445d4c5a4a105/ant2/ant2.cpp#L130
