### ISSUE TITLE
C++ casting

### ISSUE THREAD

**Issue by fan1x** [Listonoh/antColonyCpp#12]
např: https://github.com/Listonoh/antColonyCpp/blob/b2940eacb198bf486ac3827900bda433b569fce9/ant2/ant2.cpp#L66

**Comment by Listonoh** [comment]
moc nechápu co na tomhle je špatně. Děkuji za případné osvětlení :)

**Comment by fan1x** [comment]
Použít správný cast `static_cast`, `reinterpret_cast`, ... (https://en.cppreference.com/w/cpp/language/explicit_cast). Tohle je hrubý Cčkový.

**Comment by Listonoh** [comment]
https://github.com/Listonoh/antColonyCpp/blob/bbe867d3a934e11ee47104991c5d284b6bc85f73/ant2/my_plane.cpp#L127-L128

https://github.com/Listonoh/antColonyCpp/blob/bbe867d3a934e11ee47104991c5d284b6bc85f73/ant2/ant2.cpp#L81
