### ISSUE TITLE
Co vrací danná funkce?

### ISSUE THREAD

**Issue by fan1x** [Listonoh/antColonyCpp#13]
Buď okomentovat kód nebo více sebevysvětlující - nahradit tuple structurou. Není jasné na první pohled, co funkce dělá a hlavně, co je návratová hodnota

**Comment by Listonoh** [comment]
už by měla vracet struct
https://github.com/Listonoh/antColonyCpp/blob/c885a0abc755955ad8ce12ed0ba8f4698ad24576/ant2/ant.cpp#L8
