### ISSUE TITLE
Udělat konstanty (constexpr)

### ISSUE THREAD

**Issue by fan1x** [Listonoh/antColonyCpp#15]
https://github.com/Listonoh/antColonyCpp/blob/b2940eacb198bf486ac3827900bda433b569fce9/ant2/my_plane.h#L16

**Comment by Listonoh** [comment]
když se dá, daná proměná změnit v argumentu programu, tak ji nemůžu zapsat jako konstantu, ne?

**Comment by fan1x** [comment]
No, v tom případě nemůže být `constexpr` ale nic nebrání tomu, aby byla `const` 😄

**Comment by Listonoh** [comment]
ok díky, zítra budu předělávat.

**Comment by Listonoh** [comment]
https://github.com/Listonoh/antColonyCpp/blob/7593dbfd670d91bec153202acb981ac1f3ae2505/ant2/my_plane.cpp#L13-L16

**Comment by Listonoh** [comment]
stale nechápu 😅

**Comment by fan1x** [comment]
Udělat z `ALPHA`, `BETA`  konstanty. Konstanty se dají nastavovat v C++ v konstruktoru - zkus pogooglit 😉 
```
my_plane {
  ...
  const double ALPHA, BETA; 
  my_plane(...); // do the magic
}
```

**Comment by Listonoh** [comment]
https://github.com/Listonoh/antColonyCpp/blob/684642db169ffb21b01dcf7569fe517142b2acdd/ant2/myPlane.cpp#L13-L16
-> 
https://github.com/Listonoh/antColonyCpp/blob/cfa09101c315cdc404317bb4a7ce688ef166ddab/ant2/myPlane.cpp#L13-L15
a s const
