### ISSUE TITLE
Program neobsahuje zakomentovaný kód

### ISSUE THREAD

**Issue by fan1x** [Listonoh/antColonyCpp#16]
https://github.com/Listonoh/antColonyCpp/blob/b2940eacb198bf486ac3827900bda433b569fce9/ant2/ant2.cpp#L163

daný kód by v release verzi neměl být, buď smazat  pokud se budeš chtít vrátit, tak ho máš v GITu, případně pro hraní stačí vytvořit jinou branch

**Comment by Listonoh** [comment]
Už by tam být neměl, děkuji za vysvětlení. 😄
