### ISSUE TITLE
Použít raději pole než mapu

### ISSUE THREAD

**Issue by fan1x** [Listonoh/antColonyCpp#17]
https://github.com/Listonoh/antColonyCpp/blob/b2940eacb198bf486ac3827900bda433b569fce9/ant2/my_plane.h#L12

mapy jsou oproti poli pomalé, nahradit struktury poli, pokud to jde 😄

**Comment by Listonoh** [comment]
Vím že je to pomalé, ale ze začátku nevím kolik mám vrcholů a zda je množina spojitá.

**Comment by Listonoh** [comment]
Dobře, bylo to pomalé. už je to ve vektoru :) , mapu to používá jen při inputu, aby správně zařadil vrcholy.
