### ISSUE TITLE
const correctness

### ISSUE THREAD

**Issue by fan1x** [Listonoh/antColonyCpp#18]
Reference by měli být, pokud to jde `const`, to samé platí pro funkce. 
např: https://github.com/Listonoh/antColonyCpp/blob/b2940eacb198bf486ac3827900bda433b569fce9/ant2/my_plane.h#L22

**Comment by Listonoh** [comment]
https://github.com/Listonoh/antColonyCpp/blob/cbdc8fffc6437969b63a35da6e0a5a781e9bbb17/ant2/my_plane.h#L22-L24
