### ISSUE TITLE
Konzistentní pojemnovávání

### ISSUE THREAD

**Issue by fan1x** [Listonoh/antColonyCpp#19]
Vybrat jedno formátování (s podtržítky, bez, camelcase, anglicky..) pro funkce, třídy proměnné a to držet v celém kódu.
Např: 
- https://github.com/Listonoh/antColonyCpp/blob/e3ba550a34d737e57efd96fa3d905f3f4bef7bab/ant2/ant2.cpp#L44
- https://github.com/Listonoh/antColonyCpp/blob/e3ba550a34d737e57efd96fa3d905f3f4bef7bab/ant2/ant2.cpp#L21
...

**Comment by Listonoh** [comment]
snad

**Comment by fan1x** [comment]
Jak pojmenováváš třídy? 
viz: `Ant` vs. `myPlane`

**Comment by Listonoh** [comment]
hmm asi by to chtělo MyPlane no

**Comment by Listonoh** [comment]
třídy pojmenované stejně -> TakžeTakhle
