### ISSUE TITLE
Použít raději std::numeric_limits

### ISSUE THREAD

**Issue by fan1x** [Listonoh/antColonyCpp#20]
https://github.com/Listonoh/antColonyCpp/blob/e3ba550a34d737e57efd96fa3d905f3f4bef7bab/ant2/my_path.h#L7

**Comment by Listonoh** [comment]
https://github.com/Listonoh/antColonyCpp/blob/d01dc0d6704c171dc488ef1578f2acf8edcaf1d8/ant2/myPath.h#L7

https://github.com/Listonoh/antColonyCpp/blob/684642db169ffb21b01dcf7569fe517142b2acdd/ant2/ant.cpp#L47
