### ISSUE TITLE
Program spadne na zkušebních datech (facebook.in)

### ISSUE THREAD

**Issue by fan1x** [Listonoh/antColonyCpp#21]
![image](https://user-images.githubusercontent.com/2750870/65641947-6159db00-dfee-11e9-8d24-577f40eeeeac.png)

**Comment by Listonoh** [comment]
zajímavé mě nepadá ... + v debug modu ten facebook je pomalej. A vypadá to že vs to nějak threaduje...

**Comment by Listonoh** [comment]
ok našel jsem to :) +-1

https://github.com/Listonoh/antColonyCpp/blob/fd961122967e1c981072cf2c234f43ad01d848c6/ant2/myPlane.cpp#L178

**Comment by fan1x** [comment]
> zajímavé mě nepadá ... + v debug modu ten facebook je pomalej. A vypadá to že vs to nějak threaduje...

Proč myslíš, že to threaduje? Pokud to explicitně nepovolíš, tak by to nemělo threadovat :)
