### ISSUE TITLE
Předělat findPath

### ISSUE THREAD

**Issue by fan1x** [Listonoh/antColonyCpp#22]
Proč se ve findPath používá pro `missinVert` set? Udělal to lépe -> nahradit setříděným polem, ve kterém se dá binárně vyhledáváat (jsou na to `<algorithms>`)

**Comment by fan1x** [comment]
Podobné platí pro `mSet`, nešlo by to nahradit polem? A co `pheromones`, musí ty být hashmap?

**Comment by Listonoh** [comment]
V pheromones chci vzhledávat pomocí hrany tedy 2 vrcholů ... nevím o žádné jiné struktuře která to dokáže.
mSet je vektor
https://github.com/Listonoh/antColonyCpp/blob/18ca61c245c8011fbed7a957edfe922d8f0e68ca/ant2/myPlane.cpp#L42
ale jak se tak dívám nebude ani potřeba

**Comment by Listonoh** [comment]
mSet odstraněn 
https://github.com/Listonoh/antColonyCpp/blob/e623f611e88ace5730cb830752d371c909cd68ad/ant2/myPlane.cpp#L39-L63

**Comment by Listonoh** [comment]
`missingVert` je už vektor a binárně se na něm hledá
