### ISSUE TITLE
Změnit map na unordered_map

### ISSUE THREAD

**Issue by fan1x** [Listonoh/antColonyCpp#26]
`unordered_map` je hash mapa, `map` je klasický tree, myslím, že by to mělo ještě drobet zrychlit. 
Jinak, jsou daná čísla/hrany nějak omezeny, pokud ano, můžeš převést každou hranu <X;Y> na jedno číslo a můžeš to opět hodit do pole.

**Comment by Listonoh** [comment]
Čísla jsou omezeny velikostí vstupu, takže tam může být i tisíce hran. Na to bych potřeboval alespoň 32bitový číslo ... což je long no ... 2^16 (65 536)  a tím to omezit na maximum 65k vrcholů a nebo rovnou použít long long int kterej má něco okolo 2 * 2^32 (4,2 *10^9) .. dobře použiji long long dle c++11

**Comment by Listonoh** [comment]
unordered and long longed

**Comment by Listonoh** [comment]
https://github.com/Listonoh/antColonyCpp/blob/6a545f454c6043a1bb31fc687deb72a6f7447f9b/ant2/myPlane.cpp#L10-L15
