### ISSUE TITLE
V GITu je nějaký nepořádek

### ISSUE THREAD

**Issue by fan1x** [Listonoh/antColonyCpp#9]
V GITu jsou i nějaké jiné (nepatřičné) soubory... Měl by obsahovat pouze zdrojáky a projektové soubory ideálně.

**Comment by Listonoh** [comment]
už by mělo být čistěji 😁

**Comment by fan1x** [comment]
No, pořád tam jsou věci, co tam nemají dělat (třeba user). Zkus vygooglit, co se dává do GITu pro C++ a Visual Studio
